# Generated by Django 6.0.3 on 2026-03-05 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('progress', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='sessionprogress',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.session'),
        ),
        migrations.AddField(
            model_name='sessionprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_progress', to='users.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='levelprogress',
            unique_together={('student', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionprogress',
            unique_together={('student', 'session')},
        ),
    ]
