# Generated by Django 5.2.12 on 2026-03-07 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('levels', '0001_initial'),
        ('payments', '0002_initial'),
        ('progress', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='levelprogress',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='levels.level'),
        ),
        migrations.AddField(
            model_name='levelprogress',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_progress', to='payments.purchase'),
        ),
        migrations.AddField(
            model_name='levelprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='sessionprogress',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.session'),
        ),
        migrations.AddField(
            model_name='sessionprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_progress', to='users.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_course_progress'),
        ),
        migrations.AddIndex(
            model_name='levelprogress',
            index=models.Index(fields=['student', 'status'], name='idx_lp_student_status'),
        ),
        migrations.AddConstraint(
            model_name='levelprogress',
            constraint=models.UniqueConstraint(fields=('student', 'level'), name='unique_level_progress'),
        ),
        migrations.AddIndex(
            model_name='sessionprogress',
            index=models.Index(fields=['student', 'updated_at'], name='idx_sp_student_date'),
        ),
        migrations.AddIndex(
            model_name='sessionprogress',
            index=models.Index(fields=['student', 'is_completed'], name='idx_sp_student_done'),
        ),
        migrations.AddConstraint(
            model_name='sessionprogress',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_session_progress'),
        ),
    ]
