# Generated by Django 5.2.11 on 2026-03-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelprogress',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='sessionprogress',
            options={'ordering': ['-updated_at']},
        ),
    ]
