# Generated by Django 5.2.11 on 2026-03-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_alter_levelprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('syllabus_complete', 'Syllabus Complete'), ('exam_passed', 'Exam Passed'), ('exam_failed', 'Exam Failed')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionprogress',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
