# Generated by Django 5.2.11 on 2026-03-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_bookmark_unique_together_and_more'),
        ('levels', '0004_alter_week_unique_together_and_more'),
        ('payments', '0005_add_composite_indexes'),
        ('progress', '0004_alter_levelprogress_status_and_more'),
        ('users', '0006_alter_issuereport_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='levelprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sessionprogress',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='levelprogress',
            constraint=models.UniqueConstraint(fields=('student', 'level'), name='unique_level_progress'),
        ),
        migrations.AddConstraint(
            model_name='sessionprogress',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_session_progress'),
        ),
    ]
