# Generated by Django 5.2.12 on 2026-03-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_bookmark_unique_together_and_more'),
        ('levels', '0004_alter_week_unique_together_and_more'),
        ('payments', '0005_add_composite_indexes'),
        ('progress', '0005_alter_levelprogress_unique_together_and_more'),
        ('users', '0006_alter_issuereport_category_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='levelprogress',
            index=models.Index(fields=['student', 'status'], name='idx_lp_student_status'),
        ),
        migrations.AddIndex(
            model_name='sessionprogress',
            index=models.Index(fields=['student', 'updated_at'], name='idx_sp_student_date'),
        ),
        migrations.AddIndex(
            model_name='sessionprogress',
            index=models.Index(fields=['student', 'is_completed'], name='idx_sp_student_done'),
        ),
    ]
