# Generated by Django 6.0.3 on 2026-03-05 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('passing_percentage', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'levels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='levels.level')),
            ],
            options={
                'db_table': 'weeks',
                'ordering': ['order'],
                'unique_together': {('level', 'order')},
            },
        ),
    ]
