# Generated by Django 6.0.3 on 2026-03-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='level',
            name='available_until',
        ),
    ]
