# Generated by Django 5.2.11 on 2026-03-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_remove_available_from_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
