# Generated by Django 5.2.11 on 2026-03-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_alter_level_is_active_alter_week_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='week',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('level', 'order'), name='unique_week_per_level'),
        ),
    ]
