services:
  db:
    image: postgres:16-alpine
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_pass
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  dev_postgres_data:
