[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python manage.py migrate --noinput && echo '--- collectstatic ---' && python manage.py collectstatic --noinput && echo '--- starting gunicorn on port $PORT ---' && gunicorn config.wsgi:application --config gunicorn.conf.py"
healthcheckPath = "/api/v1/health/"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
