# Generated by Django 5.2.11 on 2026-03-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('levels', '0004_alter_week_unique_together_and_more'),
        ('users', '0006_alter_issuereport_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('student', 'level'), name='unique_certificate_per_level'),
        ),
    ]
