# Generated by Django 5.2.12 on 2026-04-21 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubtReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='doubts/attachments/')),
            ],
            options={
                'db_table': 'doubt_replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoubtTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('screenshot', models.ImageField(blank=True, upload_to='doubts/screenshots/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('answered', 'Answered'), ('closed', 'Closed')], db_index=True, default='open', max_length=15)),
                ('context_type', models.CharField(choices=[('session', 'Session'), ('topic', 'Topic'), ('exam_question', 'Exam Question')], db_index=True, max_length=20)),
                ('bonus_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'doubt_tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
