# Generated by Django 5.2.12 on 2026-04-21 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('doubts', '0001_initial'),
        ('exams', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doubtreply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubt_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doubtticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doubts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doubtticket',
            name='exam_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubt_tickets', to='exams.question'),
        ),
        migrations.AddField(
            model_name='doubtticket',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubt_tickets', to='courses.session'),
        ),
        migrations.AddField(
            model_name='doubtticket',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubt_tickets', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='doubtreply',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='doubts.doubtticket'),
        ),
        migrations.AddIndex(
            model_name='doubtticket',
            index=models.Index(fields=['student', 'status'], name='idx_doubt_student_status'),
        ),
    ]
