# Generated by Django 5.2.11 on 2026-03-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubtticket',
            name='context_type',
            field=models.CharField(choices=[('session', 'Session'), ('topic', 'Topic'), ('exam_question', 'Exam Question')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='doubtticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('answered', 'Answered'), ('closed', 'Closed')], db_index=True, default='open', max_length=15),
        ),
    ]
