# Generated by Django 5.2.12 on 2026-03-07 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_bookmark_unique_together_and_more'),
        ('doubts', '0003_alter_doubtticket_context_type_and_more'),
        ('exams', '0007_alter_attemptquestion_unique_together_and_more'),
        ('users', '0006_alter_issuereport_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doubtticket',
            index=models.Index(fields=['student', 'status'], name='idx_doubt_student_status'),
        ),
    ]
