# Generated by Django 5.2.12 on 2026-04-21 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('resource_type', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('note', 'Note'), ('markdown', 'Markdown')], default='', max_length=10)),
                ('markdown_content', models.TextField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('session_type', models.CharField(choices=[('video', 'Video'), ('resource', 'Resource'), ('practice_exam', 'Practice Exam'), ('proctored_exam', 'Proctored Exam')], db_index=True, default='video', max_length=20)),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['order'],
            },
        ),
    ]
