# Generated by Django 5.2.12 on 2026-03-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='file_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='session',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('note', 'Note')], default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
