# Generated by Django 5.2.11 on 2026-03-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_resource_options_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('note', 'Note')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
