# Generated by Django 5.2.12 on 2026-03-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_resource_model_add_fields_to_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='markdown_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('note', 'Note'), ('markdown', 'Markdown')], default='', max_length=10),
        ),
    ]
