# Generated by Django 5.2.11 on 2026-03-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_is_active_alter_resource_resource_type_and_more'),
        ('levels', '0004_alter_week_unique_together_and_more'),
        ('users', '0006_alter_issuereport_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(('session__isnull', False), ('week__isnull', False), _connector='OR'), name='resource_must_have_session_or_week'),
        ),
    ]
