# Generated by Django 5.2.12 on 2026-03-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_session_markdown_content_alter_session_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
