# Generated by Codex on 2026-04-08

from django.db import migrations
from django.db.models import Max


def backfill_weekly_exam_sessions(apps, schema_editor):
    Exam = apps.get_model("exams", "Exam")
    Session = apps.get_model("courses", "Session")

    for exam in Exam.objects.filter(exam_type="weekly", week__isnull=False).iterator():
        session = Session.objects.filter(exam_id=exam.pk).order_by("pk").first()
        desired_type = "proctored_exam" if exam.is_proctored else "practice_exam"
        desired_duration = exam.duration_minutes * 60

        if session is None:
            max_order = Session.objects.filter(week_id=exam.week_id).aggregate(max_order=Max("order"))["max_order"] or 0
            Session.objects.create(
                week_id=exam.week_id,
                title=exam.title,
                video_url="",
                file_url="",
                resource_type="",
                markdown_content="",
                thumbnail_url="",
                duration_seconds=desired_duration,
                order=max_order + 1,
                is_active=exam.is_active,
                session_type=desired_type,
                exam_id=exam.pk,
            )
            continue

        update_fields = []
        if session.week_id != exam.week_id:
            max_order = (
                Session.objects.filter(week_id=exam.week_id)
                .exclude(pk=session.pk)
                .aggregate(max_order=Max("order"))["max_order"]
                or 0
            )
            session.week_id = exam.week_id
            session.order = max_order + 1
            update_fields.extend(["week", "order"])
        if session.title != exam.title:
            session.title = exam.title
            update_fields.append("title")
        if session.video_url:
            session.video_url = ""
            update_fields.append("video_url")
        if session.file_url:
            session.file_url = ""
            update_fields.append("file_url")
        if session.resource_type:
            session.resource_type = ""
            update_fields.append("resource_type")
        if session.markdown_content:
            session.markdown_content = ""
            update_fields.append("markdown_content")
        if session.duration_seconds != desired_duration:
            session.duration_seconds = desired_duration
            update_fields.append("duration_seconds")
        if session.session_type != desired_type:
            session.session_type = desired_type
            update_fields.append("session_type")
        if session.is_active != exam.is_active:
            session.is_active = exam.is_active
            update_fields.append("is_active")

        if update_fields:
            session.save(update_fields=update_fields)


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0004_remove_question_course_remove_question_week_and_more"),
        ("courses", "0005_add_thumbnail_and_notification_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_weekly_exam_sessions, migrations.RunPython.noop),
    ]
