# Generated by Django 5.2.12 on 2026-04-21 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image_url', models.URLField(max_length=500)),
                ('link_type', models.CharField(choices=[('course', 'Course'), ('level', 'Level'), ('url', 'External URL'), ('none', 'No Link')], default='none', max_length=10)),
                ('link_id', models.UUIDField(blank=True, help_text='ID of the linked course/level (if link_type is course or level)', null=True)),
                ('link_url', models.URLField(blank=True, help_text='External URL (if link_type is url)', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['order'],
            },
        ),
    ]
