# Generated by Django 6.0.3 on 2026-03-05 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedbacks', to='users.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionfeedback',
            unique_together={('student', 'session')},
        ),
    ]
