# Generated by Django 5.2.12 on 2026-03-07 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedbacks', to='users.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='sessionfeedback',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_feedback_per_session'),
        ),
    ]
