# Generated by Django 5.2.11 on 2026-03-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionfeedback',
            options={'ordering': ['-created_at']},
        ),
    ]
