# Generated by Django 5.2.12 on 2026-03-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_sessionfeedback_clarity_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionfeedback',
            old_name='rating',
            new_name='overall_rating',
        ),
    ]
