# Generated by Django 5.2.11 on 2026-03-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_bookmark_unique_together_and_more'),
        ('feedback', '0004_alter_sessionfeedback_clarity_rating_and_more'),
        ('users', '0006_alter_issuereport_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionfeedback',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sessionfeedback',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_feedback_per_session'),
        ),
    ]
