# Generated by Django 5.2.12 on 2026-03-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='gateway_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='gateway_payment_id',
            new_name='razorpay_payment_id',
        ),
    ]
