# Generated by Django 5.2.11 on 2026-03-06 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_is_active_alter_resource_resource_type_and_more'),
        ('payments', '0004_alter_paymenttransaction_gateway_payment_id_and_more'),
        ('users', '0006_alter_issuereport_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['student', 'status', 'expires_at'], name='idx_purchase_access'),
        ),
    ]
