# Generated by Django 5.2.12 on 2026-03-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='onboarding_completed',
            new_name='is_onboarding_completed',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='onboarding_exam_attempted',
            new_name='is_onboarding_exam_attempted',
        ),
    ]
