# Generated by Django 5.2.11 on 2026-03-05 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('content', 'Content Issue'), ('payment', 'Payment Issue'), ('account', 'Account Issue'), ('other', 'Other')], default='other', max_length=15)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('screenshot', models.ImageField(blank=True, upload_to='issues/screenshots/')),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'issue_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
