# Generated by Django 5.2.12 on 2026-03-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_fields_clean_naming'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='admin_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='browser_info',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='device_info',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='os_info',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
