# Generated by Django 5.2.11 on 2026-03-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentprofile_onboarding_completed_issuereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='users/avatars/'),
        ),
    ]
