# Generated by Django 5.2.12 on 2026-03-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_issuereport_device_admin_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='feedback_reminder_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='issue_report_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='payment_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
