# Generated by Django 5.2.11 on 2026-03-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_change_profile_picture_to_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='category',
            field=models.CharField(choices=[('bug', 'Bug'), ('content', 'Content Issue'), ('payment', 'Payment Issue'), ('account', 'Account Issue'), ('other', 'Other')], db_index=True, default='other', max_length=15),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
