# Generated by Django 5.2.12 on 2026-04-09 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_rename_fields_clean_naming"),
        ("users", "0006_add_thumbnail_and_notification_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminStudentActionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("reset_exam_attempts", "Reset Exam Attempts"),
                            ("unlock_level", "Unlock Level"),
                            ("manual_pass", "Manual Pass"),
                            ("extend_validity", "Extend Validity"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("reason", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_admin_action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_student_action_logs",
                        to="levels.level",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_action_logs",
                        to="payments.purchase",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_action_logs",
                        to="users.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "admin_student_action_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="adminstudentactionlog",
            index=models.Index(fields=["student", "created_at"], name="idx_admin_action_student"),
        ),
        migrations.AddIndex(
            model_name="adminstudentactionlog",
            index=models.Index(fields=["action_type", "created_at"], name="idx_admin_action_type"),
        ),
    ]
