# Generated by Django 5.2.12 on 2026-03-07 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(blank=True, help_text='Text answer for fill-in-the-blank questions', max_length=500)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'attempt_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'options',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('violation_type', models.CharField(choices=[('full_screen_exit', 'Full Screen Exit'), ('tab_switch', 'Tab Switch'), ('voice_detected', 'Voice Detected'), ('multi_face', 'Multiple Faces Detected'), ('extension_detected', 'Extension Detected')], max_length=25)),
                ('warning_number', models.PositiveIntegerField()),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'proctoring_violations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=10)),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('multi_mcq', 'Multi-Select MCQ'), ('fill_blank', 'Fill in the Blank')], db_index=True, default='mcq', max_length=15)),
                ('marks', models.PositiveIntegerField(default=4)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0, help_text='Marks deducted for wrong answer (0 = no negative marking)', max_digits=5)),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering')),
                ('correct_text_answer', models.CharField(blank=True, help_text='Correct answer text for fill-in-the-blank questions', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.CharField(choices=[('weekly', 'Weekly'), ('level_final', 'Level Final'), ('onboarding', 'Onboarding')], db_index=True, max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField()),
                ('passing_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_questions', models.PositiveIntegerField()),
                ('is_proctored', models.BooleanField(default=False)),
                ('max_warnings', models.PositiveIntegerField(default=3, help_text='Max proctoring warnings before disqualification')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='courses.course')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='levels.level')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='levels.week')),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('timed_out', 'Timed Out')], db_index=True, default='in_progress', max_length=15)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_marks', models.PositiveIntegerField()),
                ('is_passed', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_disqualified', models.BooleanField(db_index=True, default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
            ],
            options={
                'db_table': 'exam_attempts',
                'ordering': ['-started_at'],
            },
        ),
    ]
