# Generated by Django 5.2.12 on 2026-04-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('levels', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='exams.examattempt'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.option'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='selected_options',
            field=models.ManyToManyField(blank=True, help_text='Selected options for multi-select MCQ questions', related_name='multi_attempts', to='exams.option'),
        ),
        migrations.AddField(
            model_name='proctoringviolation',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='exams.examattempt'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='levels.level'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'exam'], name='idx_attempt_student_exam'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status', 'is_passed', 'is_disqualified'], name='idx_attempt_leaderboard'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'started_at'], name='idx_attempt_student_started'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status', 'started_at'], name='idx_attempt_status_started'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_question_per_attempt'),
        ),
    ]
