# Generated by Django 5.2.11 on 2026-03-05 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='selected_options',
            field=models.ManyToManyField(blank=True, help_text='Selected options for multi-select MCQ questions', related_name='multi_attempts', to='exams.option'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='text_answer',
            field=models.CharField(blank=True, help_text='Text answer for fill-in-the-blank questions', max_length=500),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_proctored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_warnings',
            field=models.PositiveIntegerField(default=3, help_text='Max proctoring warnings before disqualification'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_text_answer',
            field=models.CharField(blank=True, help_text='Correct answer text for fill-in-the-blank questions', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation shown after answering'),
        ),
        migrations.AddField(
            model_name='question',
            name='negative_marks',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marks deducted for wrong answer (0 = no negative marking)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('multi_mcq', 'Multi-Select MCQ'), ('fill_blank', 'Fill in the Blank')], default='mcq', max_length=15),
        ),
        migrations.CreateModel(
            name='ProctoringViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('violation_type', models.CharField(choices=[('full_screen_exit', 'Full Screen Exit'), ('tab_switch', 'Tab Switch'), ('voice_detected', 'Voice Detected'), ('multi_face', 'Multiple Faces Detected'), ('extension_detected', 'Extension Detected')], max_length=25)),
                ('warning_number', models.PositiveIntegerField()),
                ('details', models.TextField(blank=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='exams.examattempt')),
            ],
            options={
                'db_table': 'proctoring_violations',
                'ordering': ['created_at'],
            },
        ),
    ]
