# Generated by Django 5.2.11 on 2026-03-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_exam_exam_type_alter_exam_is_active_and_more'),
        ('users', '0006_alter_issuereport_category_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'exam'], name='idx_attempt_student_exam'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status', 'is_passed', 'is_disqualified'], name='idx_attempt_leaderboard'),
        ),
    ]
