# Generated by Django 5.2.12 on 2026-04-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_remove_question_course_remove_question_week_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="detect_tab_switch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="require_fullscreen",
            field=models.BooleanField(default=False),
        ),
    ]
