# Generated by Django 5.2.11 on 2026-03-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_add_composite_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
    ]
