# Generated by Django 5.2.12 on 2026-04-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_exam_detect_tab_switch_exam_require_fullscreen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proctoringviolation",
            name="violation_type",
            field=models.CharField(
                choices=[
                    ("full_screen_exit", "Full Screen Exit"),
                    ("tab_switch", "Tab Switch"),
                    ("voice_detected", "Voice Detected"),
                    ("multi_face", "Multiple Faces Detected"),
                    ("no_face", "No Face Detected"),
                    ("extension_detected", "Extension Detected"),
                ],
                max_length=25,
            ),
        ),
    ]
