# Generated by Django 5.2.12 on 2026-03-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_attemptquestion_unique_together_and_more'),
        ('users', '0006_alter_issuereport_category_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'started_at'], name='idx_attempt_student_started'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status', 'started_at'], name='idx_attempt_status_started'),
        ),
    ]
