# Generated by Django 6.0.3 on 2026-03-05 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_revenue',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LevelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('total_passes', models.PositiveIntegerField(default=0)),
                ('total_failures', models.PositiveIntegerField(default=0)),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='levels.level')),
            ],
            options={
                'db_table': 'level_analytics',
                'ordering': ['-date'],
                'unique_together': {('level', 'date')},
            },
        ),
    ]
