# Generated by Django 5.2.12 on 2026-04-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelanalytics',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='levels.level'),
        ),
        migrations.AddConstraint(
            model_name='levelanalytics',
            constraint=models.UniqueConstraint(fields=('level', 'date'), name='unique_level_date'),
        ),
    ]
