# Generated by Django 5.2.12 on 2026-03-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='levelanalytics',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='levelanalytics',
            constraint=models.UniqueConstraint(fields=('level', 'date'), name='unique_level_date'),
        ),
    ]
