# Generated by Django 5.2.12 on 2026-04-21 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('purchase', 'Purchase'), ('exam_result', 'Exam Result'), ('doubt_reply', 'Doubt Reply'), ('level_unlock', 'Level Unlock'), ('course_expiry', 'Course Expiry'), ('general', 'General')], db_index=True, default='general', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('data', models.JSONField(blank=True, help_text='Extra payload for the client', null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
