# Generated by Django 5.2.11 on 2026-03-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('exam_result', 'Exam Result'), ('doubt_reply', 'Doubt Reply'), ('level_unlock', 'Level Unlock'), ('course_expiry', 'Course Expiry'), ('general', 'General')], db_index=True, default='general', max_length=20),
        ),
    ]
